"use server";

import { getInvoiceNotifications as getInvoiceNotificationsFlow, type InvoiceNotificationsInput } from "@/ai/flows/invoice-action-notifications";

/**
 * Wraps the AI flow in a server action for secure, server-side execution.
 * @param input - The input for the invoice notifications flow.
 * @returns The notification generated by the AI.
 */
export async function getAINotification(input: InvoiceNotificationsInput) {
  try {
    const result = await getInvoiceNotificationsFlow(input);
    return result;
  } catch (error) {
    console.error("Error in getAINotification action:", error);
    // You might want to throw a more specific error or handle it differently
    throw new Error("Failed to get AI notification.");
  }
}
